#include "lexer_tables.h"

#include <ctype.h>

#define FINAL (-1)
#define ERROR (-2)
#define N ACTION_NONE
#define T(state, action) { state, action }
#define F(action) T(FINAL, action)
#define E T(ERROR, ACTION_ERROR)
#define FINAL_ROW { F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N) }

/*
 * Las columnas de nuevo_estado y token son las 22 columnas de la spec que
 * no incluyen ESP-TAB. En proceso sí se conserva esa columna (23 columnas).
 */
const int nuevo_estado[STATE_COUNT][LEXER_TABLE_COLUMNS] = {
    { 1, 2, 4, 6, 8, 10, 12, 13, 14, 15, 16, 17, 20, 21, 22, 23, 24, 25, ERROR, 26, ERROR, ERROR },
    { 1, 1, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL },
    { FINAL, 2, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, 3, FINAL, FINAL, FINAL },
    { FINAL, 3, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL },
    { FINAL, FINAL, 5, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL },
    { FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL },
    { ERROR, ERROR, 7, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR },
    { FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL },
    { FINAL, FINAL, 9, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL },
    { FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL },
    { FINAL, FINAL, 11, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL },
    { FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL },
    { FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL },
    { FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL },
    { FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL },
    { FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL },
    { FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL },
    { FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL },
    { 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 19, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18 },
    { 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 19, 0, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18 },
    { FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL },
    { FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL },
    { FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL },
    { FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL },
    { FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL },
    { 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, FINAL, 26, 26 },
    { FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL, FINAL },
};

const LexerTransition proceso[STATE_COUNT][EVENT_COUNT] = {
    { T(1, ACTION_START_IDENTIFIER), T(2, ACTION_START_NUMBER), T(4, N), T(6, N), T(8, N), T(10, N), T(12, N), T(13, N), T(14, N), T(15, N), T(16, N), T(17, N), T(20, N), T(21, N), T(22, N), T(23, N), T(24, N), T(25, N), E, T(26, ACTION_START_STRING), T(FINAL, N), E },
    { T(1, ACTION_ACCUMULATE_IDENTIFIER), T(1, ACTION_ACCUMULATE_IDENTIFIER), F(ACTION_RECOGNIZE_IDENTIFIER), F(ACTION_RECOGNIZE_IDENTIFIER), F(ACTION_RECOGNIZE_IDENTIFIER), F(ACTION_RECOGNIZE_IDENTIFIER), F(ACTION_RECOGNIZE_IDENTIFIER), F(ACTION_RECOGNIZE_IDENTIFIER), F(ACTION_RECOGNIZE_IDENTIFIER), F(ACTION_RECOGNIZE_IDENTIFIER), F(ACTION_RECOGNIZE_IDENTIFIER), F(ACTION_RECOGNIZE_IDENTIFIER), F(ACTION_RECOGNIZE_IDENTIFIER), F(ACTION_RECOGNIZE_IDENTIFIER), F(ACTION_RECOGNIZE_IDENTIFIER), F(ACTION_RECOGNIZE_IDENTIFIER), F(ACTION_RECOGNIZE_IDENTIFIER), F(ACTION_RECOGNIZE_IDENTIFIER), F(ACTION_RECOGNIZE_IDENTIFIER), F(ACTION_RECOGNIZE_IDENTIFIER), F(ACTION_RECOGNIZE_IDENTIFIER), F(ACTION_RECOGNIZE_IDENTIFIER), F(ACTION_RECOGNIZE_IDENTIFIER) },
    { F(ACTION_RECOGNIZE_INTEGER), T(2, ACTION_ACCUMULATE_INTEGER), F(ACTION_RECOGNIZE_INTEGER), F(ACTION_RECOGNIZE_INTEGER), F(ACTION_RECOGNIZE_INTEGER), F(ACTION_RECOGNIZE_INTEGER), F(ACTION_RECOGNIZE_INTEGER), F(ACTION_RECOGNIZE_INTEGER), F(ACTION_RECOGNIZE_INTEGER), F(ACTION_RECOGNIZE_INTEGER), F(ACTION_RECOGNIZE_INTEGER), F(ACTION_RECOGNIZE_INTEGER), F(ACTION_RECOGNIZE_INTEGER), F(ACTION_RECOGNIZE_INTEGER), F(ACTION_RECOGNIZE_INTEGER), F(ACTION_RECOGNIZE_INTEGER), F(ACTION_RECOGNIZE_INTEGER), F(ACTION_RECOGNIZE_INTEGER), T(3, ACTION_START_REAL), F(ACTION_RECOGNIZE_INTEGER), F(ACTION_RECOGNIZE_INTEGER), F(ACTION_RECOGNIZE_INTEGER), F(ACTION_RECOGNIZE_INTEGER) },
    { F(ACTION_RECOGNIZE_REAL), T(3, ACTION_ACCUMULATE_REAL), F(ACTION_RECOGNIZE_REAL), F(ACTION_RECOGNIZE_REAL), F(ACTION_RECOGNIZE_REAL), F(ACTION_RECOGNIZE_REAL), F(ACTION_RECOGNIZE_REAL), F(ACTION_RECOGNIZE_REAL), F(ACTION_RECOGNIZE_REAL), F(ACTION_RECOGNIZE_REAL), F(ACTION_RECOGNIZE_REAL), F(ACTION_RECOGNIZE_REAL), F(ACTION_RECOGNIZE_REAL), F(ACTION_RECOGNIZE_REAL), F(ACTION_RECOGNIZE_REAL), F(ACTION_RECOGNIZE_REAL), F(ACTION_RECOGNIZE_REAL), F(ACTION_RECOGNIZE_REAL), F(ACTION_RECOGNIZE_REAL), F(ACTION_RECOGNIZE_REAL), F(ACTION_RECOGNIZE_REAL), F(ACTION_RECOGNIZE_REAL), F(ACTION_RECOGNIZE_REAL) },
    { F(N), F(N), T(5, N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N) },
    { F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N) },
    { E, E, T(7, N), E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E },
    { F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N) },
    { F(N), F(N), T(9, N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N) },
    { F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N) },
    { F(N), F(N), T(11, N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N) },
    { F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N), F(N) },
    FINAL_ROW,
    FINAL_ROW,
    FINAL_ROW,
    FINAL_ROW,
    FINAL_ROW,
    FINAL_ROW,
    { T(18, ACTION_IGNORE), T(18, ACTION_IGNORE), T(18, ACTION_IGNORE), T(18, ACTION_IGNORE), T(18, ACTION_IGNORE), T(18, ACTION_IGNORE), T(18, ACTION_IGNORE), T(18, ACTION_IGNORE), T(18, ACTION_IGNORE), T(18, ACTION_IGNORE), T(19, ACTION_IGNORE), T(18, ACTION_IGNORE), T(18, ACTION_IGNORE), T(18, ACTION_IGNORE), T(18, ACTION_IGNORE), T(18, ACTION_IGNORE), T(18, ACTION_IGNORE), T(18, ACTION_IGNORE), T(18, ACTION_IGNORE), T(18, ACTION_IGNORE), T(18, ACTION_IGNORE), T(18, ACTION_IGNORE), T(18, ACTION_IGNORE) },
    { T(18, N), T(18, N), T(18, ACTION_IGNORE), T(18, ACTION_IGNORE), T(18, ACTION_IGNORE), T(18, ACTION_IGNORE), T(18, ACTION_IGNORE), T(18, ACTION_IGNORE), T(18, ACTION_IGNORE), T(18, ACTION_IGNORE), T(19, ACTION_IGNORE), T(0, ACTION_IGNORE), T(18, ACTION_IGNORE), T(18, ACTION_IGNORE), T(18, ACTION_IGNORE), T(18, ACTION_IGNORE), T(18, ACTION_IGNORE), T(18, ACTION_IGNORE), T(18, ACTION_IGNORE), T(18, ACTION_IGNORE), T(18, ACTION_IGNORE), T(18, ACTION_IGNORE), T(18, ACTION_IGNORE) },
    FINAL_ROW,
    FINAL_ROW,
    FINAL_ROW,
    FINAL_ROW,
    FINAL_ROW,
    FINAL_ROW,
    { T(26, ACTION_ACCUMULATE_STRING), T(26, ACTION_ACCUMULATE_STRING), T(26, ACTION_ACCUMULATE_STRING), T(26, ACTION_ACCUMULATE_STRING), T(26, ACTION_ACCUMULATE_STRING), T(26, ACTION_ACCUMULATE_STRING), T(26, ACTION_ACCUMULATE_STRING), T(26, ACTION_ACCUMULATE_STRING), T(26, ACTION_ACCUMULATE_STRING), T(26, ACTION_ACCUMULATE_STRING), T(26, ACTION_ACCUMULATE_STRING), T(26, ACTION_ACCUMULATE_STRING), T(26, ACTION_ACCUMULATE_STRING), T(26, ACTION_ACCUMULATE_STRING), T(26, ACTION_ACCUMULATE_STRING), T(26, ACTION_ACCUMULATE_STRING), T(26, ACTION_ACCUMULATE_STRING), T(26, ACTION_ACCUMULATE_STRING), T(26, ACTION_ACCUMULATE_STRING), T(27, ACTION_RECOGNIZE_STRING), T(26, ACTION_ACCUMULATE_STRING), T(26, ACTION_ACCUMULATE_STRING), T(26, ACTION_ACCUMULATE_STRING) },
    FINAL_ROW,
};

const int token[STATE_COUNT][LEXER_TABLE_COLUMNS] = {
    { 1, 2, 4, 6, 8, 10, 12, 13, 14, 15, 16, 17, 20, 21, 22, 23, 24, 25, 27, 26, ERROR, ERROR },
    { 1, 1, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR },
    { TOKEN_INTEGER, 2, TOKEN_INTEGER, TOKEN_INTEGER, TOKEN_INTEGER, TOKEN_INTEGER, TOKEN_INTEGER, TOKEN_INTEGER, TOKEN_INTEGER, TOKEN_INTEGER, TOKEN_INTEGER, TOKEN_INTEGER, TOKEN_INTEGER, TOKEN_INTEGER, TOKEN_INTEGER, TOKEN_INTEGER, TOKEN_INTEGER, TOKEN_INTEGER, 3, TOKEN_INTEGER, TOKEN_INTEGER, TOKEN_INTEGER },
    { TOKEN_REAL, 3, TOKEN_REAL, TOKEN_REAL, TOKEN_REAL, TOKEN_REAL, TOKEN_REAL, TOKEN_REAL, TOKEN_REAL, TOKEN_REAL, TOKEN_REAL, TOKEN_REAL, TOKEN_REAL, TOKEN_REAL, TOKEN_REAL, TOKEN_REAL, TOKEN_REAL, TOKEN_REAL, TOKEN_REAL, TOKEN_REAL, TOKEN_REAL, TOKEN_REAL },
    { TOKEN_ASSIGN, TOKEN_ASSIGN, 5, TOKEN_ASSIGN, TOKEN_ASSIGN, TOKEN_ASSIGN, TOKEN_ASSIGN, TOKEN_ASSIGN, TOKEN_ASSIGN, TOKEN_ASSIGN, TOKEN_ASSIGN, TOKEN_ASSIGN, TOKEN_ASSIGN, TOKEN_ASSIGN, TOKEN_ASSIGN, TOKEN_ASSIGN, TOKEN_ASSIGN, TOKEN_ASSIGN, TOKEN_ASSIGN, TOKEN_ASSIGN, TOKEN_ASSIGN, TOKEN_ASSIGN },
    { TOKEN_EQUAL, TOKEN_EQUAL, TOKEN_EQUAL, TOKEN_EQUAL, TOKEN_EQUAL, TOKEN_EQUAL, TOKEN_EQUAL, TOKEN_EQUAL, TOKEN_EQUAL, TOKEN_EQUAL, TOKEN_EQUAL, TOKEN_EQUAL, TOKEN_EQUAL, TOKEN_EQUAL, TOKEN_EQUAL, TOKEN_EQUAL, TOKEN_EQUAL, TOKEN_EQUAL, TOKEN_EQUAL, TOKEN_EQUAL, TOKEN_EQUAL, TOKEN_EQUAL },
    { ERROR, ERROR, 7, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR },
    { TOKEN_NOT_EQUAL, TOKEN_NOT_EQUAL, TOKEN_NOT_EQUAL, TOKEN_NOT_EQUAL, TOKEN_NOT_EQUAL, TOKEN_NOT_EQUAL, TOKEN_NOT_EQUAL, TOKEN_NOT_EQUAL, TOKEN_NOT_EQUAL, TOKEN_NOT_EQUAL, TOKEN_NOT_EQUAL, TOKEN_NOT_EQUAL, TOKEN_NOT_EQUAL, TOKEN_NOT_EQUAL, TOKEN_NOT_EQUAL, TOKEN_NOT_EQUAL, TOKEN_NOT_EQUAL, TOKEN_NOT_EQUAL, TOKEN_NOT_EQUAL, TOKEN_NOT_EQUAL, TOKEN_NOT_EQUAL, TOKEN_NOT_EQUAL },
    { TOKEN_LESS, TOKEN_LESS, 9, TOKEN_LESS, TOKEN_LESS, TOKEN_LESS, TOKEN_LESS, TOKEN_LESS, TOKEN_LESS, TOKEN_LESS, TOKEN_LESS, TOKEN_LESS, TOKEN_LESS, TOKEN_LESS, TOKEN_LESS, TOKEN_LESS, TOKEN_LESS, TOKEN_LESS, TOKEN_LESS, TOKEN_LESS, TOKEN_LESS, TOKEN_LESS },
    { TOKEN_LESS_EQUAL, TOKEN_LESS_EQUAL, TOKEN_LESS_EQUAL, TOKEN_LESS_EQUAL, TOKEN_LESS_EQUAL, TOKEN_LESS_EQUAL, TOKEN_LESS_EQUAL, TOKEN_LESS_EQUAL, TOKEN_LESS_EQUAL, TOKEN_LESS_EQUAL, TOKEN_LESS_EQUAL, TOKEN_LESS_EQUAL, TOKEN_LESS_EQUAL, TOKEN_LESS_EQUAL, TOKEN_LESS_EQUAL, TOKEN_LESS_EQUAL, TOKEN_LESS_EQUAL, TOKEN_LESS_EQUAL, TOKEN_LESS_EQUAL, TOKEN_LESS_EQUAL, TOKEN_LESS_EQUAL, TOKEN_LESS_EQUAL },
    { TOKEN_GREATER, TOKEN_GREATER, 11, TOKEN_GREATER, TOKEN_GREATER, TOKEN_GREATER, TOKEN_GREATER, TOKEN_GREATER, TOKEN_GREATER, TOKEN_GREATER, TOKEN_GREATER, TOKEN_GREATER, TOKEN_GREATER, TOKEN_GREATER, TOKEN_GREATER, TOKEN_GREATER, TOKEN_GREATER, TOKEN_GREATER, TOKEN_GREATER, TOKEN_GREATER, TOKEN_GREATER, TOKEN_GREATER },
    { TOKEN_GREATER_EQUAL, TOKEN_GREATER_EQUAL, TOKEN_GREATER_EQUAL, TOKEN_GREATER_EQUAL, TOKEN_GREATER_EQUAL, TOKEN_GREATER_EQUAL, TOKEN_GREATER_EQUAL, TOKEN_GREATER_EQUAL, TOKEN_GREATER_EQUAL, TOKEN_GREATER_EQUAL, TOKEN_GREATER_EQUAL, TOKEN_GREATER_EQUAL, TOKEN_GREATER_EQUAL, TOKEN_GREATER_EQUAL, TOKEN_GREATER_EQUAL, TOKEN_GREATER_EQUAL, TOKEN_GREATER_EQUAL, TOKEN_GREATER_EQUAL, TOKEN_GREATER_EQUAL, TOKEN_GREATER_EQUAL, TOKEN_GREATER_EQUAL, TOKEN_GREATER_EQUAL },
    { TOKEN_AND, TOKEN_AND, TOKEN_AND, TOKEN_AND, TOKEN_AND, TOKEN_AND, TOKEN_AND, TOKEN_AND, TOKEN_AND, TOKEN_AND, TOKEN_AND, TOKEN_AND, TOKEN_AND, TOKEN_AND, TOKEN_AND, TOKEN_AND, TOKEN_AND, TOKEN_AND, TOKEN_AND, TOKEN_AND, TOKEN_AND, TOKEN_AND },
    { TOKEN_OR, TOKEN_OR, TOKEN_OR, TOKEN_OR, TOKEN_OR, TOKEN_OR, TOKEN_OR, TOKEN_OR, TOKEN_OR, TOKEN_OR, TOKEN_OR, TOKEN_OR, TOKEN_OR, TOKEN_OR, TOKEN_OR, TOKEN_OR, TOKEN_OR, TOKEN_OR, TOKEN_OR, TOKEN_OR, TOKEN_OR, TOKEN_OR },
    { TOKEN_PLUS, TOKEN_PLUS, TOKEN_PLUS, TOKEN_PLUS, TOKEN_PLUS, TOKEN_PLUS, TOKEN_PLUS, TOKEN_PLUS, TOKEN_PLUS, TOKEN_PLUS, TOKEN_PLUS, TOKEN_PLUS, TOKEN_PLUS, TOKEN_PLUS, TOKEN_PLUS, TOKEN_PLUS, TOKEN_PLUS, TOKEN_PLUS, TOKEN_PLUS, TOKEN_PLUS, TOKEN_PLUS, TOKEN_PLUS },
    { TOKEN_MINUS, TOKEN_MINUS, TOKEN_MINUS, TOKEN_MINUS, TOKEN_MINUS, TOKEN_MINUS, TOKEN_MINUS, TOKEN_MINUS, TOKEN_MINUS, TOKEN_MINUS, TOKEN_MINUS, TOKEN_MINUS, TOKEN_MINUS, TOKEN_MINUS, TOKEN_MINUS, TOKEN_MINUS, TOKEN_MINUS, TOKEN_MINUS, TOKEN_MINUS, TOKEN_MINUS, TOKEN_MINUS, TOKEN_MINUS, TOKEN_MINUS },
    { TOKEN_MULTIPLY, TOKEN_MULTIPLY, TOKEN_MULTIPLY, TOKEN_MULTIPLY, TOKEN_MULTIPLY, TOKEN_MULTIPLY, TOKEN_MULTIPLY, TOKEN_MULTIPLY, TOKEN_MULTIPLY, TOKEN_MULTIPLY, TOKEN_MULTIPLY, TOKEN_MULTIPLY, TOKEN_MULTIPLY, TOKEN_MULTIPLY, TOKEN_MULTIPLY, TOKEN_MULTIPLY, TOKEN_MULTIPLY, TOKEN_MULTIPLY, TOKEN_MULTIPLY, TOKEN_MULTIPLY, TOKEN_MULTIPLY, TOKEN_MULTIPLY },
    { TOKEN_DIVIDE, TOKEN_DIVIDE, TOKEN_DIVIDE, TOKEN_DIVIDE, TOKEN_DIVIDE, TOKEN_DIVIDE, TOKEN_DIVIDE, TOKEN_DIVIDE, TOKEN_DIVIDE, TOKEN_DIVIDE, TOKEN_DIVIDE, 18, TOKEN_DIVIDE, TOKEN_DIVIDE, TOKEN_DIVIDE, TOKEN_DIVIDE, TOKEN_DIVIDE, TOKEN_DIVIDE, TOKEN_DIVIDE, TOKEN_DIVIDE, TOKEN_DIVIDE, TOKEN_DIVIDE },
    { 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 19, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18 },
    { 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 19, 0, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18 },
    { TOKEN_OPEN_PAREN, TOKEN_OPEN_PAREN, TOKEN_OPEN_PAREN, TOKEN_OPEN_PAREN, TOKEN_OPEN_PAREN, TOKEN_OPEN_PAREN, TOKEN_OPEN_PAREN, TOKEN_OPEN_PAREN, TOKEN_OPEN_PAREN, TOKEN_OPEN_PAREN, TOKEN_OPEN_PAREN, TOKEN_OPEN_PAREN, TOKEN_OPEN_PAREN, TOKEN_OPEN_PAREN, TOKEN_OPEN_PAREN, TOKEN_OPEN_PAREN, TOKEN_OPEN_PAREN, TOKEN_OPEN_PAREN, TOKEN_OPEN_PAREN, TOKEN_OPEN_PAREN, TOKEN_OPEN_PAREN, TOKEN_OPEN_PAREN },
    { TOKEN_CLOSE_PAREN, TOKEN_CLOSE_PAREN, TOKEN_CLOSE_PAREN, TOKEN_CLOSE_PAREN, TOKEN_CLOSE_PAREN, TOKEN_CLOSE_PAREN, TOKEN_CLOSE_PAREN, TOKEN_CLOSE_PAREN, TOKEN_CLOSE_PAREN, TOKEN_CLOSE_PAREN, TOKEN_CLOSE_PAREN, TOKEN_CLOSE_PAREN, TOKEN_CLOSE_PAREN, TOKEN_CLOSE_PAREN, TOKEN_CLOSE_PAREN, TOKEN_CLOSE_PAREN, TOKEN_CLOSE_PAREN, TOKEN_CLOSE_PAREN, TOKEN_CLOSE_PAREN, TOKEN_CLOSE_PAREN, TOKEN_CLOSE_PAREN, TOKEN_CLOSE_PAREN },
    { TOKEN_OPEN_BRACE, TOKEN_OPEN_BRACE, TOKEN_OPEN_BRACE, TOKEN_OPEN_BRACE, TOKEN_OPEN_BRACE, TOKEN_OPEN_BRACE, TOKEN_OPEN_BRACE, TOKEN_OPEN_BRACE, TOKEN_OPEN_BRACE, TOKEN_OPEN_BRACE, TOKEN_OPEN_BRACE, TOKEN_OPEN_BRACE, TOKEN_OPEN_BRACE, TOKEN_OPEN_BRACE, TOKEN_OPEN_BRACE, TOKEN_OPEN_BRACE, TOKEN_OPEN_BRACE, TOKEN_OPEN_BRACE, TOKEN_OPEN_BRACE, TOKEN_OPEN_BRACE, TOKEN_OPEN_BRACE, TOKEN_OPEN_BRACE },
    { TOKEN_CLOSE_BRACE, TOKEN_CLOSE_BRACE, TOKEN_CLOSE_BRACE, TOKEN_CLOSE_BRACE, TOKEN_CLOSE_BRACE, TOKEN_CLOSE_BRACE, TOKEN_CLOSE_BRACE, TOKEN_CLOSE_BRACE, TOKEN_CLOSE_BRACE, TOKEN_CLOSE_BRACE, TOKEN_CLOSE_BRACE, TOKEN_CLOSE_BRACE, TOKEN_CLOSE_BRACE, TOKEN_CLOSE_BRACE, TOKEN_CLOSE_BRACE, TOKEN_CLOSE_BRACE, TOKEN_CLOSE_BRACE, TOKEN_CLOSE_BRACE, TOKEN_CLOSE_BRACE, TOKEN_CLOSE_BRACE, TOKEN_CLOSE_BRACE, TOKEN_CLOSE_BRACE },
    { TOKEN_SEMICOLON, TOKEN_SEMICOLON, TOKEN_SEMICOLON, TOKEN_SEMICOLON, TOKEN_SEMICOLON, TOKEN_SEMICOLON, TOKEN_SEMICOLON, TOKEN_SEMICOLON, TOKEN_SEMICOLON, TOKEN_SEMICOLON, TOKEN_SEMICOLON, TOKEN_SEMICOLON, TOKEN_SEMICOLON, TOKEN_SEMICOLON, TOKEN_SEMICOLON, TOKEN_SEMICOLON, TOKEN_SEMICOLON, TOKEN_SEMICOLON, TOKEN_SEMICOLON, TOKEN_SEMICOLON, TOKEN_SEMICOLON, TOKEN_SEMICOLON },
    { TOKEN_COMMA, TOKEN_COMMA, TOKEN_COMMA, TOKEN_COMMA, TOKEN_COMMA, TOKEN_COMMA, TOKEN_COMMA, TOKEN_COMMA, TOKEN_COMMA, TOKEN_COMMA, TOKEN_COMMA, TOKEN_COMMA, TOKEN_COMMA, TOKEN_COMMA, TOKEN_COMMA, TOKEN_COMMA, TOKEN_COMMA, TOKEN_COMMA, TOKEN_COMMA, TOKEN_COMMA, TOKEN_COMMA, TOKEN_COMMA },
    { 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 27, 26, 26 },
    { TOKEN_STRING, TOKEN_STRING, TOKEN_STRING, TOKEN_STRING, TOKEN_STRING, TOKEN_STRING, TOKEN_STRING, TOKEN_STRING, TOKEN_STRING, TOKEN_STRING, TOKEN_STRING, TOKEN_STRING, TOKEN_STRING, TOKEN_STRING, TOKEN_STRING, TOKEN_STRING, TOKEN_STRING, TOKEN_STRING, TOKEN_STRING, TOKEN_STRING, TOKEN_STRING, TOKEN_STRING },
};

const ReservedWord reserved_words[] = {
    { "inicio", TOKEN_START },
    { "entero", TOKEN_INTEGER_TYPE },
    { "real", TOKEN_REAL_TYPE },
    { "si", TOKEN_IF },
    { "sino", TOKEN_ELSE },
    { "para", TOKEN_FOR },
    { "imprimir", TOKEN_PRINT },
    { "retornar", TOKEN_RETURN }
};

const size_t reserved_words_count = sizeof(reserved_words) / sizeof(reserved_words[0]);

int get_evento(int character)
{
    if (isalpha((unsigned char) character))
        return EVENT_LETTER;
    if (isdigit((unsigned char) character))
        return EVENT_DIGIT;

    switch (character) {
    case '=': return EVENT_EQUAL;
    case '!': return EVENT_NOT;
    case '<': return EVENT_LESS;
    case '>': return EVENT_GREATER;
    case '&': return EVENT_AND;
    case '|': return EVENT_OR;
    case '+': return EVENT_PLUS;
    case '-': return EVENT_MINUS;
    case '*': return EVENT_MULTIPLY;
    case '/': return EVENT_SLASH;
    case '(': return EVENT_OPEN_PAREN;
    case ')': return EVENT_CLOSE_PAREN;
    case '{': return EVENT_OPEN_BRACE;
    case '}': return EVENT_CLOSE_BRACE;
    case ';': return EVENT_SEMICOLON;
    case ',': return EVENT_COMMA;
    case '.': return EVENT_DOT;
    case '"': return EVENT_QUOTE;
    default:
        return isspace((unsigned char) character) ? EVENT_SPACE : EVENT_OTHER;
    }
}

int get_table_evento(int event)
{
    if (event == EVENT_SPACE)
        return -1;
    return event > EVENT_SPACE ? event - 1 : event;
}

#undef FINAL_ROW
#undef E
#undef F
#undef T
#undef N
#undef ERROR
#undef FINAL
